version: '3.8'
services:
  shlink_db:
    image: postgres:12.1
    container_name: shlink-db
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: postgres
      POSTGRES_DB: shlink
    ports:
      - "127.0.0.1:5432:5432"
    restart: always
    networks:
      shlink_network:
        ipv4_address: 10.0.0.2
  shlink_stable:
    image: shlinkio/shlink:stable
    container_name: shlink-stable
    depends_on:
      - shlink_db
    ports:
      - "8081:8080"
    environment:
      DEFAULT_DOMAIN: ${DEFAULT_DOMAIN}
      IS_HTTPS_ENABLED: "true"
      GEOLITE_LICENSE_KEY: ${GEOLITE_LICENSE_KEY}
      DB_DRIVER: postgres
      DB_USER: postgres
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_HOST: shlink-db
    networks:
      shlink_network:
        ipv4_address: 10.0.0.3
networks:
  shlink_network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/24
          gateway: 10.0.0.1
